### PR TITLE
Bug fix: Removed nested anchor elements.

### PR DESCRIPTION
**Pull request by Norman-Amy**
The closing tag of the inner anchor had been closing the outer anchor.

Reviewed-by: Rose Sadler

### CODE REVIEW

**Comment by lambertsteven** [comment]
If both anchor tags were created, doesn't that mean that both the `openPersonCard` and `openPersonPage` options were set to true? I don't think that having both options set to true is a valid use case since you either want the link to take you directly to the person page via `openPersonPage` or you want the link to open the person card via `openPersonCard`.

**Comment by Norman-Amy** [comment]
openPersonCard was true, but openPersonPage was false, so the inner link to the person page wasn't there, but its closing anchor tag was, so the span that came after it was no longer a link. I changed it so it's gated on openPersonPage and it only looks for openPersonCard if openPersonPage is false.

**Comment by lambertsteven** [comment]
Wait, so `ng-if` left the inner anchor tags closing tag even when the value was false?

**Comment by Norman-Amy** [comment]
Correct

**Comment by lambertsteven** [comment]
I think I know what happened. Angular parses the complete DOM tree first before applying values to the ng stuff. That means that the two anchor tags are created, then removed if their `ng-if` values are false. But since the were already there first, the invalid HTML state happens.

What if instead of duplicating the DOM, we only add the `data-cmd` attributes if the `openPersonCard` option is true, that way we can use the same anchor tag (which already has the href to the person page)?

**Comment by Norman-Amy** [comment]
That could work. We could change the logic in the javascript to add the attribute based on the options passed in, then remove the inner anchor element altogether.

**Comment by Norman-Amy** [comment]
I haven't worked in fsModules very much, so just to be sure, should I add the logic to the viewModel or directive for fsPersonVitals?

**Comment by lambertsteven** [comment]
You'll need to add it to both `fsPersonVitals.directive.js` and `ngFsPersonVitals.directive.js`

**Comment by Norman-Amy** [comment]
Ok. Thanks!

**Comment by Norman-Amy** [comment]
Ok, Steven. Changes are in. Let me know what you think!

**Pull request merged**
